### ISSUE TITLE
layout.partition

### ISSUE THREAD

**Issue by canardo** [spaced/scala-js-d3#11]
Hi there - thanks for the great job, I enjoyed it a lot already. Any reason why partition got dropped in the moduled rewrite? Which other layout is the best example to mimic so I can add it?

**Comment by spaced** [comment]
The reason is very simple: missed here too: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/master/d3/d3.d.ts. I have to investigate why this is happen.

**Comment by spaced** [comment]
PR welcome

**Comment by canardo** [comment]
Woehoe, thanks a lot! Christmas present :)

**Comment by spaced** [comment]
fyi: not yet released. you have to clone and sbt publishLocal to use it. Btw. layout part is still not very handy. See also #8
