### ISSUE TITLE
Cannot use call

### ISSUE THREAD

**Issue by nghuuphuoc** [spaced/scala-js-d3#12]
I followed the simple code taken from [AxisTest.scala](https://github.com/spaced/scala-js-d3/blob/master/src/test/scala/org/singlespaced/d3js/AxisTest.scala)

``` scala
val x = d3.time.scale().range(js.Array(0,  1000))
val xAxis = d3.svg.axis().scale(x).orient("bottom").ticks(5)
d3.select("p").append("svg").call(xAxis)
```

but the compiler/IDE reports that `call` expects a `js.Function`, not `Axis`.

**Comment by spaced** [comment]
was fixed with #5. will release asap release 0.2.0

**Comment by nghuuphuoc** [comment]
Thank you. I look forward to the next release.

**Comment by spaced** [comment]
fyi: release 0.1.2 contains also this fix

**Comment by nghuuphuoc** [comment]
Awesome :+1:
