### ISSUE TITLE
Possible issue to selection.data

### ISSUE THREAD

**Issue by akarasev** [spaced/scala-js-d3#18]
Hello,

I'm trying to adapt an example to render a simple HTML-table from [here](https://github.com/mbostock/d3/wiki/Selections#data).

Here is my [code](https://gist.github.com/akarasev/bb37e4d085368d31ff84).

Code compiled successful, but when page is loading, I have the error: 

> Uncaught scala.scalajs.runtime.UndefinedBehaviorError: An undefined behavior was detected: undefined is not an instance of java.lang.Integer scalajsenv.js:192

May be I do something wrong. For example, I cannot implement a `text()` method. Take a look, please.

Thanks

**Comment by spaced** [comment]
not your fault: text was without a function, and the other one had to do with the imlicits and undefined x parameter on DatumFunction.

**Comment by spaced** [comment]
btw will release soon 0.3.1 and your example.

**Comment by akarasev** [comment]
I am looking forward to the new version. Thanks for your efforts!

**Comment by spaced** [comment]
version 0.3.1 is now available, see also working example here https://github.com/spaced/scala-js-d3-example-app/blob/table_data_example/src/main/scala/example/ScalaJSExample.scala, branch `table_data_example`

**Comment by akarasev** [comment]
Thank you!
