### ISSUE TITLE
Key function signature does not seem to match d3 documentation

### ISSUE THREAD

**Issue by arnolddevos** [spaced/scala-js-d3#19]
The BaseSelection#data method's key argument has type js.ThisFunction2[Datum|NewDatum,js.UndefOr[NewDatum], Int, String]

But the 'this' argument of the key function would be a DOM node or an Array according to d3 documentation here:
https://github.com/mbostock/d3/wiki/Selections#data

Also, the documentation does not mention that the 'd' argument could be undefined.  

Perhaps a plain js.Function2[Datum, Int, String] would be better here?   It would certainly be easier to use.  Supplying a function with the current signature is a pain.

**Comment by arnolddevos** [comment]
Rereading the d3 documentation (and testing), it seems undefined can be supplied to the key function. So a signature of js.Function2[js.UndefOr[NewDatum], Int, String] would be needed.

**Comment by spaced** [comment]
Can you give me an example or even better a unit test to describe your expectation? See also here: 
https://github.com/spaced/scala-js-d3/blob/master/src/test/scala/org/singlespaced/d3js/SelectionTest.scala

Because there are other fixed issues descibed in #4 and #9. See also my comment https://github.com/spaced/scala-js-d3/issues/4#issuecomment-158797765

**Comment by arnolddevos** [comment]
Based on all that, my issue boils down to: why Datum|NewDatum in the signature of the key function, s.ThisFunction2[Datum|NewDatum,js.UndefOr[NewDatum], Int, String] ?

I will write some test code and come back.

**Comment by arnolddevos** [comment]
Here is a gist to demonstrate the key function arguments: https://gist.github.com/arnolddevos/12972edcfee584333181  (I ran the given code in the browser and collected the log.)

As per d3 documentation, the 'this' argument is either a js.Node or js.Array[Datum].  (In the example Datum=Int.)  

So the signature can be js.ThisFunction2[dom.Node|js.Array[Datum], js.UndefOr[NewDatum], Int, String] or js.Function2[js.UndefOr[NewDatum], Int, String] if we don't care about 'this'.

I can do a PR.

edited: type param / can do PR
