### ISSUE TITLE
example

### ISSUE THREAD

**Issue by omidb** [spaced/scala-js-d3#2]
I was trying to run an example of it in the workbench-example-app autowire skeleton. I couldn't run it, I got different errors. Would you please add example that runs with the lib?

**Comment by rhz** [comment]
Hi. Yes, an example would be great. In particular, how do you create an instance of Layout.GraphForceNode?

**Comment by javadba** [comment]
joining the crowd. pls provide at least a single reasonable example.  you must have something around for your testing work (there are no test classes either..)

**Comment by spaced** [comment]
Better late than never:
https://github.com/spaced/scala-js-d3-example-app
