### ISSUE TITLE
Empty update selection

### ISSUE THREAD

**Issue by netzwerg** [spaced/scala-js-d3#20]
First and foremost: Thanks for you library!

When playing around with it, I ran into an issue with the update selection returned by `selectAll(..).data(..)`. Given the following html:

``` html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
</head>
<body>

<!-- Include JavaScript dependencies -->
<script type="text/javascript" src="./target/scala-2.11/scala-js-playground-jsdeps.js"></script>

<!-- Include Scala.js compiled code -->
<script type="text/javascript" src="./target/scala-2.11/scala-js-playground-fastopt.js"></script>

<!-- Run JSApp -->
<script type="text/javascript" src="./target/scala-2.11/scala-js-playground-launcher.js"></script>

<svg>
    <text y="50">Hello</text>
    <text y="100">World</text>
</svg>

</body>
</html>
```

and the following Scala.js:

``` Scala
import org.singlespaced.d3js.d3
import scala.scalajs.js

object DemoApp extends js.JSApp {

  def main(): Unit = {
    val data = js.Array("0")
    d3.select("body svg").selectAll("text").data(data).style("fill", "orange")
  }

}
```

I would expect "Hello" to be rendered in orange (the array contains one datum, so there should be one match in the update selection). However, the selection is empty and both text elements appear in black.

The equivalent JS would be:

``` JS
d3.select("body svg").selectAll("text").data(["0"]).style("fill", "orange")
```

If I manually enter it in the Chrome Console, everything works as expected.

**Comment by spaced** [comment]
Works as expected using my https://github.com/spaced/scala-js-d3-example-app. 
Put the  `svg` tag before 

```
<!-- Run JSApp -->
<script type="text/javascript" src="./target/scala-2.11/scala-js-playground-launcher.js"></script>
```

**Comment by netzwerg** [comment]
That did the trick, tx!
