### ISSUE TITLE
Question on radial

### ISSUE THREAD

**Issue by giampaolotrapasso** [spaced/scala-js-d3#21]
Hi,

I'm trying to make this code work but it does not compile

``` scala
val line = d3.svg.line.radial().interpolate("basis").tension(0).radius(100)
```

Is something wrong in what I wrote or simply this function is not supported yet? I saw the a radial trait is present in code but it does not seem connected to the rest of the code.

**Comment by spaced** [comment]
First: `radial`, `radius` and `angle` are missed on `svg.line`. tnx for your input.
I tried to add those functions and ran in to another bug: `d3.svg.line` is not the same as `d3.svg.line()`, and `d3.svg.line().radial()` will fail.

**Comment by giampaolotrapasso** [comment]
Thanks!
