### ISSUE TITLE
Testing with uTest

### ISSUE THREAD

**Issue by phosphene** [spaced/scala-js-d3#23]
Thanks for the fine work. I'm curious as to what are the best examples for, or bases for, writing tests for the use of this facade with uTest. I see some tests in src/test. But I don't see anything other than a skeleton for the example.

Thanks so much.

**Comment by spaced** [comment]
Not sure what you expect:
Examples for use of the d3 facade are here https://github.com/spaced/scala-js-d3-example-app (branches)
Utests examples like this one? https://github.com/spaced/scala-js-d3/blob/master/src/test/scala/org/singlespaced/d3js/AxisTest.scala?

**Comment by phosphene** [comment]
Thanks and my apologies for the ambiguity of my question. I was working with the example app. I modified the build.sbt to use phantomjs and I created a pull request for that. My question was a general one. I'm looking for the best idioms and/or I'm looking to benefit from your experience with writing uTests for this facade. Those tests such as your AxisTest are helpful.

**Comment by phosphene** [comment]
Forgive me for the pull request that adds 'scalaJSUseRhino in Global := false' to build.sbt

I see that you recommend this in the example.

> set scalaJSStage in Global := FastOptStage

I'm curious as to your favored choice as you use one way in one project and and another in the other project?

**Comment by spaced** [comment]
tnx. for PR. rhino fails with d3lib
