### ISSUE TITLE
.each and d3.select(this)

### ISSUE THREAD

**Issue by whazor** [spaced/scala-js-d3#24]
In the .each function of d3, often code is executed as `d3.select(this)`. However as far as my knowledge goes, in scala.js d3 it is not possible to currently perform this action.

One possibility would be using the ThisFunction from scala.js, this would allow the usage of this as an parameter.

**Comment by spaced** [comment]
Sorry for the late answer:
yes. `ThisFunction` helps here.

**Comment by benderpremier** [comment]
Shouldn't this also be done in 
```scala
@js.native
trait Transition[Datum] extends BaseDom[Datum,Transition[Datum]]
.
.
.
  def each(`type`: String, listener: js.Function2[Datum, Double, Any]): Transition[Datum] = js.native

  def each(listener: js.Function2[Datum, Double, Any]): Transition[Datum] = js.native
```
in https://github.com/spaced/scala-js-d3/blob/master/src/main/scala/org/singlespaced/d3js/misc.scala ?
