### ISSUE TITLE
selection.data

### ISSUE THREAD

**Issue by daenenk** [spaced/scala-js-d3#4]
The current implementation requires a `Function3` as key function.

``` scala
def data[NewDatum](data: js.Array[NewDatum], key:js.Function3[NewDatum, Int, Int, String]): Update[NewDatum] = js.native
```

This implementation gives execution errors when running with d3.js (master 20 May 2015 > tag 3.5.9)
complaining that the 3 argument is undefined iso Int.

The d3.js documentation only describes a function with one or two arguments: datum and index.

This can be corrected :

``` scala
def data[NewDatum](data: js.Array[NewDatum], key: js.Function2[NewDatum, Int, String]): Update[NewDatum] = js.native
```

**Comment by spaced** [comment]
Its even more complicated:
The key function is called twice during the data binding process, which proceeds in two phases. 
 key function must be a `js.ThisFunction2[Datum|NewDatum,js.UndefOr[NewDatum], Int, String]`
In first loop `d` is `undefined`, `this` is `Datum`
In second loop `d` is `NewDatum` and `this` is  also `NewDatum`
See also http://stackoverflow.com/questions/27577368/d3-js-key-function-running-twice-on-simple-selector-array-combo

**Comment by spaced** [comment]
Please reopen if you are not happy with the solution.

**Comment by daenenk** [comment]
Indeed, it is more complex than I initially thought. Have a look to the example I posted on the force layout Issue; it is related. 
Would it make sense to bound the NewDatum?

``` scala
def data[NewDatum <: Datum]( ...
```
