### ISSUE TITLE
axis as function

### ISSUE THREAD

**Issue by daenenk** [spaced/scala-js-d3#5]
In javascript `axis` as-is can be used as a function.
In scala this is supported by the apply functions.

``` scala
trait Axis extends js.Any { 
 def apply(selection: Selection[js.Any]): Unit = js.native
 def apply(selection: Transition[js.Any]): Unit = js.native
```

However this makes it hard to pass an axis as argument to the selection.call() function,
as in e.g. from [Simple d3.js Graph](http://bl.ocks.org/d3noob/b3ff6ae1c120eea654b5])

``` js
svg
   .append("g")
   .attr("class", "x axis")
   .call(xAxis)
```

I suggest the following:

``` scala
trait Axis extends js.Function1[ Selection[js.Any] | Transition[js.Any], Unit] 
```

**Comment by spaced** [comment]
Tnx for feedback, Several other traits are functions too. Need to check it too.

**Comment by daenenk** [comment]
Works fine now! thx
