### ISSUE TITLE
Node trait

### ISSUE THREAD

**Issue by daenenk** [spaced/scala-js-d3#8]
I was looking for a better way to create Node instances, i.s.o. ( see example posted in [Issue 6](https://github.com/spaced/scala-js-d3/issues/6))

``` scala
def apply(id: String): Node = {
      val n = new js.Object().asInstanceOf[Node]
      n.id = id
      n
    }
```

First, I changed trait `forceModule.Node` into a class 

``` scala
package forceModule {  . . .

@js.annotation.ScalaJSDefined
class Node extends js.Object {
  var index: Double = 0  // or null.asInstanceOf[Double]
  var x: Double = 0
  var y: Double = 0
  var px: Double = 0
  var py: Double = 0
  var fixed: Boolean = false // or null.asInstanceOf[Boolean]
  var weight: Double = 0
}

 . . . }
```

So I could change the object creation in the example into:

``` scala
object ForceLayoutExample extends JSApp { . . .

@js.annotation.ScalaJSDefined
class Node(val id: String) extends forceModule.Node

object Node {
  def apply(id:String): Node = new Node(id)
}

. . . }
```

While wondering whether it was a good idea to turn `forceModule.Node` into a class, I realised that `Node` is not defined as a class in d3.js; actually it is not defined at all. The API accepts or produces an object with the members `x`, `y`, etc, without explicitly defining a javascript class for it. This is interesting, because this means that there is not a strict reason to define the trait `forceModule.Node` as `@js.native`. This gives more flexibility form a scala perspective. As long as the objects that we pass to the d3.js API have the expected var members, it should be fine.

I'm relatively new into scala-js but I tried the following (complete other approach than above) and it works as well:

``` scala
package forceModule {  . . .

// no js.native! 
trait Node {
  var index: Double
  var x: Double
  var y: Double
  var px: Double
  var py: Double
  var fixed: Boolean
  var weight: Double
}

import js.annotation.JSExport
@JSExport
class DefaultNode extends Node { // alternatively init the vars to null
  @JSExport var index: Double = 0
  @JSExport var x: Double = 0
  @JSExport var y: Double = 0
  @JSExport var px: Double = 0
  @JSExport var py: Double = 0
  @JSExport var fixed: Boolean = false
  @JSExport var weight: Double = 0
}

. . . }

object ForceLayoutExample extends JSApp { . . .

case class Node(id: String) extends forceModule.DefaultNode

. . . }
```

I could even define a `case class` which would be not allowed extending from a js.native trait.

Some food for though ...

**Comment by spaced** [comment]
you may check the new approach: a data node for layouts must not extends Node. But user can extend from and use all available variables.
